#Inquisitor course profiles
#Mon Apr 27 20:41:30 CEST 2026
course.1.counts=1_ij_basics.qa.md\=3;2_ij_characters.qa.md\=2;3_ij_themes.qa.md\=2
course.1.name=Wallace
course.1.path=./Wallace_questions
course.2.counts=1_lynch_films.qa.md\=2;2_lynch_twin_peaks.qa.md\=2;3_lynch_style.qa.md\=2
course.2.name=Lynch
course.2.path=./Lynch_questions
course.3.counts=
course.3.name=IOTST
course.3.path=/Users/dpatti/Library/CloudStorage/GoogleDrive-xedivad@gmail.com/My Drive/TEACHING/IOTST/QIOTST2026
courses=1,2,3
