#Inquisitor course profiles
#Tue Mar 24 16:36:28 CET 2026
course.1.counts=1_ij_basics.qa\=3;2_ij_characters.qa\=2;3_ij_themes.qa\=2
course.1.name=TEST COURSE
course.1.path=/Users/dpatti/IdeaProjects/Inquisitor/Test_questions
courses=1
