# Inquisitor Electron profile
profile.name=Test
profile.compilePdf=true
profile.selectedCourse=2
courses=1,2,3
course.1.name=Wallace
course.1.path=/Users/dpatti/IdeaProjects/Inquisitor/example_questions/Wallace_questions
course.1.heading=Wallace
course.1.subheading=
course.1.totalExams=8
course.1.totalStudents=120
course.1.counts=1_ij_basics.qa.md=3;2_ij_characters.qa.md=2;3_ij_themes.qa.md=2
course.2.name=Lynch
course.2.path=/Users/dpatti/IdeaProjects/Inquisitor/example_questions/Lynch_questions
course.2.heading=Lynch
course.2.subheading=
course.2.totalExams=8
course.2.totalStudents=120
course.2.counts=1_lynch_films.qa.md=2;2_lynch_twin_peaks.qa.md=2;3_lynch_style.qa.md=2
course.3.name=IOTST
course.3.path=/Users/dpatti/Library/CloudStorage/GoogleDrive-xedivad@gmail.com/My Drive/TEACHING/IOTST/2026/EXA/QIOTST2026
course.3.heading=IOTST
course.3.subheading=
course.3.totalExams=8
course.3.totalStudents=120
course.3.counts=1_microcontrollers-basics.qa.md=1;3_digitalanalog.qa.md=1;5a_interfaces.qa.md=1;5b_protocols.qa.md=1;ES_IO_dma_new.qa.md=1;ES_IO_dma.qa.md=1;ES_IO_int.qa.md=2;ES_IO_poll.qa.md=1;ESP32_comp.qa.md=1
